# This is a config file for image-to-phone training.
# This is based on the XNMT 12_speech.yaml example.
# Compared to the conventional attentional model, we remove input embeddings,
# instead directly read in a feature vector the pyramidal LSTM reduces length of
# the input sequence by a factor of 2 per layer (except for the first layer).
# Output units should be characters according to the paper.
!Experiment
  name: speech
  exp_global: !ExpGlobal
    save_num_checkpoints: 2
    default_layer_dim: 512
    dropout: 0.1
  model: !DefaultTranslator
    src_embedder: !NoopEmbedder
      emb_dim: 512
    encoder: !PyramidalLSTMSeqTransducer
      layers: 3
      downsampling_method: concat
      reduce_factor: 2
      input_dim: 512
      hidden_dim: 64
    attender: !MlpAttender
      state_dim: 64
      hidden_dim: 64
      input_dim: 64
    decoder: !AutoRegressiveDecoder
      embedder: !SimpleWordEmbedder
        emb_dim: 64
      rnn: !UniLSTMSeqTransducer
        layers: 1
      transform: !AuxNonLinear
        output_dim: 64
      bridge: !CopyBridge {}
    src_reader: !H5Reader
      transpose: True
    trg_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: phone_types.txt}
      output_proc: join-char
  train: !SimpleTrainingRegimen
    run_for_epochs: 25
    batcher: !SrcBatcher
      pad_src_to_multiple: 4
      batch_size: 3
    trainer: !AdamTrainer {}
    src_file: flickr40k_cnnfeats_train.h5
    trg_file: flickr40k_phones_train.txt
    dev_tasks:
      - !LossEvalTask
        src_file: flickr40k_cnnfeats_dev.h5
        ref_file: flickr40k_phones_dev.txt
      - !AccuracyEvalTask
        eval_metrics: bleu,wer
        src_file: flickr40k_cnnfeats_dev.h5
        ref_file: flickr40k_phones_dev.txt
        hyp_file: flickr40k_phones_dev_hyp.txt
        inference: !AutoRegressiveInference
          batcher: !InOrderBatcher
            _xnmt_id: inference_batcher
            pad_src_to_multiple: 4
            batch_size: 1
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: bleu,wer
      src_file: flickr40k_cnnfeats_test.h5
      ref_file: flickr40k_phones_test.txt
      hyp_file: flickr40k_phones_test_hyp.txt
      inference: !AutoRegressiveInference
        batcher: !Ref { name: inference_batcher }
